# Asignación cuadrática 

#### función objetivo 
$$ f(\sigma) = \sum_{i=1}^n \sum_{j=1}^n d_{ij}f_{\sigma(i) \sigma(j)} $$


#### espacio de búsqueda
permitaciones de $\sigma$, sin ciclos ni inversiones: 
$$\Omega = \frac{(n-1)!}{2}$$


In [267]:
import numpy as np
from math import sqrt

# definicion de la funcion objetivo
def f(sigma):
    function = 0
    for i in range(0,len(D)):
        for j in range(0,len(D)):
            function = function +  D[i][j] * F[sigma[i]][sigma[j]] 
    return function

def dist(r1,r2):
    return np.linalg.norm(r1-r2)

In [348]:
import matplotlib.pyplot as plt

x1 = np.array([1,1])
x2 = np.array([1,2])
locations = [x1,x2]

nol = len(locations) # number of locations 
D = np.zeros([nol,nol])
for i in range(0,len(D)):
    for j in range(0,len(D)):
        D[i][j] = dist(locations[i],locations[j])
 
F = np.random.rand(nol,nol)*0 +1

In [349]:
print(F)

[[1. 1.]
 [1. 1.]]


In [350]:
np.sum(F)/2

4.0

In [277]:
sigma = [1,0]
f(sigma)

0.6932278284948129

In [344]:
class graph:
    vertexs  = []
    branchs = []
    widths = []
    def __init__(self,vertexs,branchs):
        self.vertexs = vertexs
        self.branchs = branchs
    def __str__(self):
        return "%s" % self.vertexs

In [345]:
x = graph(1,2)

In [346]:
print(x)

1


In [353]:
x = [ 3,4]

In [357]:
x[False]

3

In [359]:
x = np.array([1,2,3])

In [363]:
x[False,True,False]

array([], shape=(0, 3), dtype=int64)

In [367]:
x = np.array([1,0,1,0])

In [368]:
np.where (x)

(array([0, 2]),)

In [369]:
np.array(x)

array([1, 0, 1, 0])